### ISSUE TITLE
严重问题： ReadFileHeadbyte     获取不到理想值望大佬回复

### ISSUE THREAD

**Issue by DevSoft2016** [dotnet-campus/EncodingNormalior#10]
我有一个json文件 使用  ReadFileHeadbyte  方法 获取的是GB2132   但实际编码是UTF 8

**Comment by lindexi** [comment]
其实获取到的只是一个期望值而已，所以不能保证判断是对的

**Comment by lindexi** [comment]
如果一个文件的 Head 是不存在的，例如你读取的 Head 实际上是 `{` 等，那么这个值是不对的

这个 Head 是文件自己写入的，所以可能被文件骗了

通过 Head 判断的方法叫 BOM 详细请看 [Byte order mark - Wikipedia](https://en.wikipedia.org/wiki/Byte_order_mark )
