### ISSUE TITLE
一直停留正在扫描的界面，一直扫描system32/build目录下的文件

### ISSUE THREAD

**Issue by mixml** [dotnet-campus/EncodingNormalior#20]
如图所示：![image](https://user-images.githubusercontent.com/16316668/72711857-ddcb8780-3ba4-11ea-959f-ad321bdf72e1.png)

**Comment by lindexi** [comment]
@mixml 多谢反馈，这货原来是 VS 的锁定功能，让这个文件处于我在读但是读不返回，我在开始修改了
