### ISSUE TITLE
刚刚（2020-02-29 11:20:54左右）编译了新版的插件，依然一直停留正在扫描的界面，一直扫描system32/build目录下的文件

### ISSUE THREAD

**Issue by mixml** [dotnet-campus/EncodingNormalior#26]
![image](https://user-images.githubusercontent.com/16316668/75600030-a1fdd900-5ae5-11ea-8bb0-77aa17258b83.png)

![image](https://user-images.githubusercontent.com/16316668/75600042-b6da6c80-5ae5-11ea-985c-10ce23610db5.png)

vs工程使用cmake构建的。

**Comment by lindexi** [comment]
@mixml 特别感谢反馈，这里的 System32 是你的工程的还是 C 盘的那个文件夹？

**Comment by lindexi** [comment]
我现在添加白名单，忽略了 .vs 文件夹的扫描了，但是要求你的  我的文档\Account.json 文件不存在，这是他的配置文件。可以在菜单里面点击设置，添加 .vs\ 文件夹忽略

![图片](https://user-images.githubusercontent.com/16054566/75603123-848d3700-5b06-11ea-88bf-643a56cd81ea.png)

**Comment by mixml** [comment]
@lindexi 修改Account.json 文件夹，增加.vs\\\r\n后解决了，谢谢。

**Comment by lindexi** [comment]
@mixml 特别感谢
