### ISSUE TITLE
请求支持VS 2022

### ISSUE THREAD

**Issue by LuohuaRain** [dotnet-campus/EncodingNormalior#39]

**Comment by lindexi** [comment]
@LuohuaRain 收到，这就安排上

**Comment by LuohuaRain** [comment]
👀

**Comment by LuohuaRain** [comment]
辛苦大佬了 终于等到了，vs marketplace里已经安装上了，感谢！
![image](https://user-images.githubusercontent.com/37979368/148030770-aa1159f7-87ca-4aa0-b872-37668aacebe4.png)

**Comment by lindexi** [comment]
@LuohuaRain 6
