### ISSUE TITLE
在自動偵測以外，能否提供設置原始編碼的選項，我想使用Big5

### ISSUE THREAD

**Issue by craftwar** [dotnet-campus/EncodingNormalior#8]
想把Big5轉utf-8

**Comment by lindexi** [comment]
big5 还在开发中 @craftwar

**Comment by lindexi** [comment]
我暂时无法分辨出 Big5 的编码

**Comment by lindexi** [comment]
@craftwar 我尝试做一个提交做之前 VS 自带的 SaveWithEncoding 的功能

https://github.com/dotnet-campus/EncodingNormalior/pull/13

**Comment by lindexi** [comment]
@craftwar 现在已经支持了，欢迎下载[插件](https://marketplace.visualstudio.com/items?itemName=lindexigd.vs-extension-18109 )试试
